# -*- coding: utf-8 -*-
"""Trabalho de Conclusão de Curso

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sLl_PV7UOhHuPlceF1m_gI82Y0dcgmdV

###**Evolução da Netflix Como produtora de Entretenimento**
"""

import pandas as pd
df =pd.read_csv('trabalho_de_conclusão_netflix.csv')
df